import { Footer } from "../../components/Footer";
import { LngSwitcher } from "../../components/LngSwitcher";
import * as prismic from "@prismicio/client";
import sm from "../../sm.json";
import { components } from "../../slices";
import { SliceZone } from "@prismicio/react";
import { useRouter } from "next/router";
import Head from "next/head";

export const getServerSideProps = async (context) => {
  //gets params from the index /params
  const { lng } = context.params;
  //contects to prismicClient
  //just to make the params match the prismic locals
  const getLanguage = (lng) => {
    if (lng == "de") return "en-de";
    if (lng == "fr") return "fr-fr";
  };
  const client = prismic.createClient(sm.apiEndpoint);
  const page = await client.getByUID("homepage", "startseite", {
    lang: getLanguage(lng),
  });
  return {
    props: { page },
  };
};
const Page = ({ page }) => {
  const router = useRouter();
  const { lng } = router.query;

  const handleLanguage = (e) => {
    if (e.target.checked) {
      router.push("/de");
    } else {
      router.push("/fr");
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto h-screen flex flex-col">
        <nav className=" flex justify-between pt-4 ">
          <span>{page.type}</span>
          <LngSwitcher handleLanguage={handleLanguage} lng={lng} />
        </nav>
        <section className=" py-24 grow">
          <SliceZone slices={page.data.slices} components={components} />
        </section>
        <Footer />
      </main>
    </>
  );
};
export default Page;
