// Code generated by Slice Machine. DO NOT EDIT.

import Footer from './Footer';
import HeroHeading from './HeroHeading';
import HomepageImageHeading from './HomepageImageHeading';

export {
	Footer,
	HeroHeading,
	HomepageImageHeading,
};

export const components = {
	footer: Footer,
	hero_heading: HeroHeading,
	homepage_image_heading: HomepageImageHeading,
};
