// Code generated by Slice Machine. DO NOT EDIT.

import HeroHeading from './HeroHeading';
import HomepageImageHeading from './HomepageImageHeading';

export {
	HeroHeading,
	HomepageImageHeading,
};

export const components = {
	hero_heading: HeroHeading,
	homepage_image_heading: HomepageImageHeading,
};
