import Head from "next/head";
import { useEffect } from "react";
import { useRouter } from "next/router";
const Page = ({ page }) => {
  const router = useRouter();
  useEffect(() => {
    console.log(navigator.language);
    if (navigator.language === "de-DE") {
      router.push("/de");
    } else if (navigator.language == "fr-fr") {
      router.push("/fr");
    } else {
      router.push("/de");
    }
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};
export default Page;
