import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Image from "next/image";

export default function Home() {
  const title = "text-6xl";
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto">
        {/* Navbar logo links + languages switcher rechts */}
        <nav></nav>
        <section className="h-screen py-24">
          {/* div with 2 boxes both 50 % widht only first box with content  */}
          <div className="w-full h-1/2">
            <div className="w-1/2 pr-14">
              <h1 className={title}>
                Showcase your thought provoking topics and ideas
              </h1>
              <p className="text-xl bold">
                Big company announcement or simple Sub-header taking two or more
                lines.
              </p>
            </div>
          </div>
          {/* div with 2 boxes both 50% left image right heading+text+button */}
          <div className="grid grid-cols-2 gap-28 w-full h-1/2 ">
            <div className="block relative w-full h-full">
              <Image
                src="https://developers.elementor.com/docs/assets/img/elementor-placeholder-image.png"
                alt=""
                fill
              ></Image>
            </div>

            <div className="flex flex-col justify-between ">
              <h1 className={title}>Big company announcement</h1>
              <p className="text-xl bold">
                Big company announcement or simple sub-header taking two or more
                lines.
              </p>
              <button className="px-14 py-3 bg-blue-600 w-fit rounded-lg text-white">
                Button
              </button>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
